version: '3'
services:
  react-app:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  signalling-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  # sfu:
  #   image: pionwebrtc/ion-sfu:latest-jsonrpc
  #   ports:
  #     - '5000-5200:5000-5200/udp'
  #     - '7000:7000'
