version: '3'
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  signalling:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  sfu:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    ports:
      - '5000-5200:5000-5200/udp'
      - '7000:7000'
# volumes:
#   caddy_data:
#     external: true
#   caddy_config:
